/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getRestaurantInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'name' : IDL.Text,
          'upiId' : IDL.Text,
          'phoneNumber' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'updatePhoneNumber' : IDL.Func([IDL.Text], [], []),
  'updateUPIId' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getRestaurantInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'name' : IDL.Text,
            'upiId' : IDL.Text,
            'phoneNumber' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'updatePhoneNumber' : IDL.Func([IDL.Text], [], []),
    'updateUPIId' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };