/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface Review {
  'starsCount' : bigint,
  'customerName' : string,
  'productName' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'addMenuItem' : ActorMethod<[string, string, bigint], undefined>,
  'addReview' : ActorMethod<[string, string, bigint, string], undefined>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getRestaurantInfo' : ActorMethod<
    [],
    { 'name' : string, 'upiId' : string, 'phoneNumber' : string }
  >,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'updatePhoneNumber' : ActorMethod<[string], undefined>,
  'updateUPIId' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];